### ISSUE TITLE
Fix huge margins for wide resolutions

### ISSUE THREAD

**Issue by guilhermedeandrade** [LauraBeatris/laurabeatris.com#29]
**_If this is the desired design, sorry for creating this issue and just ignore it._** 

I realized that for wide resolutions the margins are way too big:

![image](https://user-images.githubusercontent.com/8797405/105852251-239f0500-5fdc-11eb-93c3-8fe8f16307cd.png)

I guess that a potential fix for this would be changing the [`maxW` value of the container](https://github.com/LauraBeatris/laurabeatris.com/blob/0c7444a78af87eca0e5c81bdf3eeb717342e1d39/components/Layout/Container/index.tsx#L6) for the [`80em` breakpoint](https://chakra-ui.com/docs/theming/theme#breakpoints).

**Comment by LauraBeatris** [comment]
That's the desired design. I decided to switch with this max-width value because I want to restrict the length of the heading and paragraph. 

But thanks for creating the issue!
