### ISSUE TITLE
TypeError: Cannot read property 'categories' of undefined components/ProjectFilters/index.tsx

### ISSUE THREAD

**Issue by Cally99** [LauraBeatris/laurabeatris.com#59]
Hi there,

Thanks for sharing your lovely portfolio site. It's really well made.
I've tried to run this project but I have an error on line 46.

```
  const filters = [
    {
      title: 'Categories',
  
      items: transformedStack.categories

    }
  ]

TypeError: Cannot read property 'categories' of undefined
```

Do you know how to fix this error? 
Thank you!

**Comment by LauraBeatris** [comment]
I think you would need to have the CMS running in order to the API data

**Comment by Cally99** [comment]
Thanks Laura for responding. I don't see in the documentation how to start the CMS server? Is there an endpoint I need to map or when I run yarn dev should it start?

**Comment by LauraBeatris** [comment]
@Cally99 The CMS data comes from my personal GraphCMS workspace, thus I'm not able to share it 

So it's hard to run this repo in other machines if you don't have access to the source of data I'm using, perhaps having some sort of mock server would solve this

**Comment by LauraBeatris** [comment]
@Cally99 I'll close this issue and clarify the README.md file that it's not possible to fully execute the repo without having access to the CMS data
